apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: {{ .Values.app.name}}-deployment 
spec: 
  replicas: {{ .Values.app.replicas}} 
  selector: 
    matchLabels: 
      app: {{ .Values.app.name}} 
  template: 
    metadata: 
      labels: 
        app: {{ .Values.app.name}} 
    spec: 
      containers: 
      - name: {{ .Values.app.name}} 
        image: {{ .Values.app.name}}: {{ .Values.app.tag}} 
        resources: 
          requests: 
            memory: {{ .Values.app.resources.memory.requests}} 
            cpu: {{ .Values.app.resources.cpu.requests}} 
          limits: 
            memory: {{ .Values.app.resources.memory.limits}} 
            cpu: {{ .Values.app.resources.cpu.limits}} 
        livenessProbe: 
          httpGet: 
            path: {{ .Values.app.path}} 
            port: {{ .Values.app.port}} 
          initialDelaySeconds: 3 
          periodSeconds: 5 
        readinessProbe: 
          tcpSocket: 
            port: {{ .Values.app.port}} 
          initialDelaySeconds: 3 
          periodSeconds: 5 
        ports: 
        - containerPort: {{ .Values.app.port}}