apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Values.app.name}}-service 
spec: 
  type: ClusterIP 
  selector: 
    app: {{ .Values.app.name}} 
  ports: 
    - protocol: {{ .Values.app.protocol}} 
      port: {{ .Values.app.port}} 
      targetPort: {{ .Values.app.port}}