app: 
  name: gurkan-ngninx-app 
  image: gurkandedeakay/demo:0.1
  tag: 0.1 
  port: 80 
  host: app.gurkan.me
  replicas: 1 
  resources: 
    cpu: 
      requests: 150m 
      limits: 200m 
    memory: 
      requests: 64Mi 
      limits: 128Mi 
  livenessProbe: 
    path: / 
    port: 80 
  readinessProbe: 
    port: 80
  protocol: TCP 